#include <iostream>
#include <storm/api/storm.h>
#include <cupaal/baum.h>
#include "cuddObj.hh"
#include <storm/models/Model.h>

class MarkovChain {
    int a{5};
    storm::dd::DdManager<storm::dd::DdType::CUDD> dd;
public:
    explicit MarkovChain(const std::shared_ptr<storm::models::symbolic::Model<storm::dd::DdType::CUDD>>& model) {
        this->dd = std::move(model->getManager());
    }

    void print() const {
        std::cout << "Hello, World!" << a << std::endl;
    }
};

void alpha(std::shared_ptr<storm::models::symbolic::Model<storm::dd::DdType::CUDD>> model, std::vector<std::tuple<std::string, double>> observations);
void beta(std::shared_ptr<storm::models::symbolic::Model<storm::dd::DdType::CUDD>> model, std::vector<std::tuple<std::string, double>> observations);
void update_parameter_estimates(std::string alpa_values, std::string beta_values, std::set<carl::Variable> variables);

// Other functions
void gamma();
void psi();
void into_semiring();
void into_numeric();
// + various other helpers like summing etc.

// Matrix functions as ADD functions
void hadamard_product();
void hadamard_division();
void kronecker_product();
void scalar();
void dot_product();

// api
void parse_and_build_model();
void generate_training_set();


int main(int argc, char* argv[]) {
    const auto model = parser::parseAndBuildPrism("some file path");

    auto transitions = model->getTransitionMatrix();
    auto labels = model->getLabels();
    auto initial = model->getInitialStates();

    auto actions = model->getStates(labels[0]);
    auto parameters = model->getParameters();

    auto rows = model->getRowVariables();
    auto cols = model->getColumnVariables();

    auto teb = model->getType();

    std::vector<std::tuple<std::string, double>> observations;

    observations.emplace_back("a", 0.2);
    observations.emplace_back("b", 1.2);

    alpha(model, observations);
    beta(model, observations);

    update_parameter_estimates("alpha", "beta", parameters);
    // prism file, timed/untimed, #observations, length_of_observations, min_parameter_value, max_parameter_value
    // Other variables: epsilon? verbosity?

    // training set of observations (potentially generated by generate_training_set or generate_observation_sequence)
    // set seed for random engine.

    model = read_and_parse_prismfile(arg1);
    observations = generate_obsetvations(model, arg2, arg3, arg4);
    parameters = fit_parameters(model, observations);





    return 0;
}